### ISSUE TITLE
Cant Install, Repo missing

### ISSUE THREAD

**Issue by Dexxa1024** [KloxoNGCommunity/kloxong#53]
I keep getting this everytime i try and install

base                                                     | 3.6 kB     00:00
extras                                                   | 2.9 kB     00:00
kloxong-copr                                             | 3.3 kB     00:00
kloxong-copr-httpd24                                     | 3.3 kB     00:00
kloxong-google-mod-pagespeed                             |  951 B     00:00
kloxong-ius                                              | 1.3 kB     00:00
kloxong-ius-archive                                      | 1.3 kB     00:00
kloxong-mariadb                                          | 2.9 kB     00:00
kloxong-nginx                                            | 2.9 kB     00:00
kloxong-nginx-stable                                     | 2.9 kB     00:00
https://repo.kloxong.org/kloxong/release/neutral/noarch/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: repo.kloxong.org; Unknown error"
Trying other mirror.

 One of the configured repositories failed (KloxoNG - release-neutral-noarch),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=kloxong-release-neutral-noarch ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable kloxong-release-neutral-noarch
        or
            subscription-manager repos --disable=kloxong-release-neutral-noarch

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=kloxong-release-neutral-noarch.skip_if_unavailable=true

failure: repodata/repomd.xml from kloxong-release-neutral-noarch: [Errno 256] No more mirrors to try.
**https://repo.kloxong.org/kloxong/release/neutral/noarch/repodata/repomd.xml: [Errno 14] curl#6 - "Could not resolve host: repo.kloxong.org; Unknown error"**
[root@vps ~]#

**Comment by luckytanuki** [comment]
Te repo is live so may be a connectivity problem. What happens if you `wget https://repo.kloxong.org/kloxong/release/neutral/noarch/repodata/repomd.xml` ?
Also `dig repo.kloxong.org` ?

**Comment by Dexxa1024** [comment]
I get ; <<>> DiG 9.11.4-P2-RedHat-9.11.4-9.P2.el7 <<>> repo.kloxong.org
;; global options: +cmd
;; connection timed out; no servers could be reached

Ive just reinstalled the server and going to test again, Im using centos 7 on oneprovider

**Comment by dkstiler** [comment]
The Repository is online from my end.  it seems a connection problem from your isp. First try to use dns servers from google or opendns to resolv properly  at your /etc/resolv.conf

**Comment by Dexxa1024** [comment]
I tried it on another vps from another provider and it worked perfect, :-)

**Comment by dkstiler** [comment]
Then it is resolved closing the issue
