### ISSUE TITLE
Kloxo Slave?

### ISSUE THREAD

**Issue by Dexxa1024** [KloxoNGCommunity/kloxong#54]
is there a slave feature like on kloxo and kloxo mr? how do you o it if there is

**Comment by dkstiler** [comment]
Yes that feature also exists here, you can utilize it in the same way of kloxomr. After the installation finishes as normal on the machine you need to act as slave you simply need to run the script make-slave

**Comment by Dexxa1024** [comment]
Thank you :-)

And keep p the good work :-)
