### ISSUE TITLE
No IP Addresses Under localhost

### ISSUE THREAD

**Issue by kentchenseo** [KloxoNGCommunity/kloxong#80]
I could not get an ip address to be registered in Kloxong after the initial install
![Kloxong bug](https://user-images.githubusercontent.com/85861109/121852470-1b90f900-cd22-11eb-9951-ccd04d9d3188.png)
, I went to admin — Servers — localhost — {IP Addresses} and clicked on Re Read IP Address, but no IP is register

**Comment by luckytanuki** [comment]
# @kentchenseo 

Hi can you email to info@kloxong.org the results of running 
`ifconfig`
and 
`sh /script/sysinfo`

**Comment by kentchenseo** [comment]
Have sent an email with the regarding info. Thanks!

**Comment by luckytanuki** [comment]
In case anyone has this problem in the future, the network interfaces need to be manually configured. 

The ifcfg-* files in /etc/sysconfig/network-scripts are used to determine the ip addresses

Kloxo looks for the following parameters.
DEVICE, IPADDR, NETMASK, ONBOOT, GATEWAY, USERCTL, PEERDNS, TYPE, IPV6INIT, BOOTPROTO

The interface needs a defined device name,  ipaddress, netmask and gateway for it to be read by Kloxo.
