### ISSUE TITLE
install fix error

### ISSUE THREAD

**Issue by lotxcsp** [KloxoNGCommunity/kloxong#82]
Hello, First of all. nice to meet you.
I tried to install this version of kloxo for testing and the first problem I encountered is a malfunctioning https in rpm (503) https://repo.ius.io/. please change this rpm with http or replace.
another problem that is not fixed since kloxo (lx) is that alias for __kloxo (kloxoscript) to work phpinfo from the control panel you can use in /opt/configs/apache/tpl:
` AliasMatch "^/__kloxo/(.*)" "/home/<?=$user;?>/kloxoscript/$1"

	<Directory "/home/<?=$user;?>/kloxoscript/">
		AllowOverride None
		<IfVersion < 2.4>
			Order allow,deny
			Allow from all
		</IfVersion>
		<IfVersion >= 2.4>
			Require all granted
		</IfVersion>
	</Directory>
`

**Comment by luckytanuki** [comment]
Not sure what is going on with IUS. Their own files yum config files uses https eg: baseurl = https://repo.ius.io/7/$basearch/
Will have to run a test install to see.

I've successfully tested the phpinfo fix and will implement in the next release.

**Comment by lotxcsp** [comment]
they return 503 to any wget attempt on https. on http works

**Comment by lotxcsp** [comment]
is it possible to give up the current dns configuration for dns and add dns as an A record for subdomains like cpanel? to give up those under subdomains (cp, states, etc.) for a subdomain. and automatic updating of ssl (Let's Encrypt) when adding subdomains?

**Comment by luckytanuki** [comment]
> they return 503 to any wget attempt on https. on http works

Can you give me a example? 
Also which version of Centos - 6 or 7?

**Comment by luckytanuki** [comment]
> is it possible to give up the current dns configuration for dns and add dns as an A record for subdomains like cpanel? to give up those under subdomains (cp, states, etc.) for a subdomain. and automatic updating of ssl (Let's Encrypt) when adding subdomains?

The first part is raised in issue #15 and I will look at it for a future update. Auto Let's Encrypt would be good.

**Comment by lotxcsp** [comment]
centos 7:


Transaction Summary
================================================================================
Install                        59 Packages (+39 Dependent packages)
Skipped (dependency problems)   2 Packages

Total download size: 37 M
Installed size: 129 M
Downloading packages:
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-bcmath-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-cli-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-common-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-dba-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-dbg-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-devel-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-embedded-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-enchant-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-fpm-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-gd-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-gmp-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-imap-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-interbase-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-intl-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-ioncube-loader-10.2.0-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-ldap-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-litespeed-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-mbstring-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-mcrypt-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-mssql-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-mysqlnd-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-odbc-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pdo-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pear-1.10.5-1.ius.el7.noarch.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pecl-apcu-4.0.11-2.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pecl-apcu-devel-4.0.11-2.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pecl-gearman-1.1.2-3.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pecl-geoip-1.0.8-9.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pecl-igbinary-2.0.5-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pecl-igbinary-devel-2.0.5-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pecl-jsonc-1.3.10-2.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pecl-jsonc-devel-1.3.10-2.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.
https://repo.ius.io/archive/7/x86_64/packages/p/php56u-pecl-krb5-1.1.2-2.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable
Trying other mirror.

**Comment by luckytanuki** [comment]
> Downloading packages:
> https://repo.ius.io/archive/7/x86_64/packages/p/php56u-bcmath-5.6.40-1.ius.el7.x86_64.rpm: [Errno 14] HTTPS Error 503 - Service Unavailable

It is looking like there is a fault with the IUS repo as others are reporting the same error as an issue on the IUS Github.

I'm going investigate forking the IUS PHP packages into KloxoNGCommunity so we can guarantee working downloads.

**Comment by lotxcsp** [comment]
I would like to be able to help the community with a mirror site in the near future. for this moment I will try to test the part with php7 (I have been waiting for an update for a long time, I also tried at some point such an update to php 7.3 but left it out due to lack of time)

**Comment by luckytanuki** [comment]
> ok, for this moment it is enough to modify https in http until they solve the problem

IUS seems to have fixed the problem.
