### ISSUE TITLE
upgrade to qmail 1.06

### ISSUE THREAD

**Issue by luckytanuki** [KloxoNGCommunity/kloxong#83]
Multiple qmail issues suggest an upgrade to qmail 1.06 would a wise idea. 

I suspect the debian source and pathces could be a good start.

**Comment by luckytanuki** [comment]
Probably https://notes.sagredo.eu/en/qmail-notes-185/qmail-vpopmail-dovecot-roberto-s-qmail-notes-8.html is the best source. The 1.06 patch has fixes for the known issues.

**Comment by luckytanuki** [comment]
After some changes to patches I have been able to build 1.06 on copr.
There are some difference in SMTP auth parameters and other configuration setting that will need to be addressed and tested.

**Comment by kloxoNG** [comment]
This has been done in Kloxo 8
