### ISSUE TITLE
Php versions for el 8

### ISSUE THREAD

**Issue by luckytanuki** [KloxoNGCommunity/kloxong#92]
Currently source php versions from IUS but IUS doesn't support el8 . 

Will have to switch over to remi version however remi uses different package naming convention to IUS and this breaks the php installation scripts .

**Comment by luckytanuki** [comment]
EL 8 will require modifying the installation scripts for PHP and MariaDB. Rewriting the installer to use the Remi safe repositories instead of the IUS will provide system php and multiple php version up from 5.4 to 8.1 . Remi packages put the files in different locations to the IUS installer. This should also work with EL 7 distributions.

**Comment by kloxoNG** [comment]
Kloxong and Kloxo 8 now use remi php
