### ISSUE TITLE
Kloxo Does not start up after reboot of server

### ISSUE THREAD

**Issue by hzm170** [KloxoNGCommunity/kloxong#96]
okay so working on a fix for this now.. When ever you reboot your server, the kloxo does not start up, even if you restarted or start the kloxo it self does noting.. 

Working on fix/update to this soon

**Comment by luckytanuki** [comment]
Ok. A few questions. 
Which release is installed? 
Which OS?
Do you see any Kloxo processes if you run ` netstat -ltnp | grep kloxo` from the command line?
Do you see any error messages when restarting Kloxo?
Run sh /script/restart - is there any errors in Kloxo's log files in the /usr/local/lxlabs/kloxo/log directory?

**Comment by hzm170** [comment]
Which release is installed? 
Which OS? Centos 7.9
Do you see any Kloxo processes if you run netstat -ltnp | grep kloxo from the command line? 
[root@c999963369-cloudpro-195388078 ~]# netstat -ltnp | grep kloxo
tcp        0      0 0.0.0.0:7777            0.0.0.0:*               LISTEN      2272/kloxo-hiawatha 
tcp        0      0 0.0.0.0:7778            0.0.0.0:*               LISTEN      2272/kloxo-hiawatha 


Do you see any error messages when restarting Kloxo?
Run sh /script/restart

Redirecting to /bin/systemctl restart kloxo-web.service
-------------------------------------------------------------------

Redirecting to /bin/systemctl restart kloxo-php.service
-------------------------------------------------------------------

Redirecting to /bin/systemctl restart kloxo-wrap.service
-------------------------------------------------------------------
Noting showing anything on my end... 

but the panel it self still down so, I been trying to look in the logs but can't access it via with small phone atm..




==============================================

**Comment by luckytanuki** [comment]
Netstat shows that Kloxo is listening on ports 7777 and 7778 so may be being blocked by a firewall 

Unless you specifically disable or configure it, centos 7's firewall will restart at reboot with the default rules.

Try flushing the firewall with the command iptables -F

If you can access Kloxo after that then you need to add rules to the firewall to allow traffic to ports 7777 and 7778 ,

**Comment by kloxoNG** [comment]
Running
`systemctl stop firewalld `
and
`systemctl disable firewalld`

will stop and disable the firewall. You probably should change the firewall settings to allow these ports through. May consider adding this function to future Kloxo versions
