### ISSUE TITLE
Network error: Software caused connection abort

### ISSUE THREAD

**Issue by Fyou3** [KloxoNGCommunity/kloxong#99]
Hi,

I am trying to install KloxoNG on Centos 7 and it is not possible.
A lot of mirrors are dead. I tried to install through this command:
https://github.com/KloxoNGCommunity/kloxong/blob/master/how-to-install.txt

... I reached the last step:  sh /script/upcp
then it starts to install KloxoNG and after 3 minutes the installation "freezes".
It stays like this (see pic.):  https://i.imgur.com/DRfBUYV.png

.. and it stays that way for a long time and at the end the connection is lost with a message "Network error: Software caused connection abort"
Img -> https://i.imgur.com/mc7kuKy.png

Is the same thing happening to anyone else? 
The VPS has 2 cores and 8 GB of RAM
So far I've tried the installation 7 times and the same thing always happens. :(

**Comment by luckytanuki** [comment]
I will have to test an install to make sure a new problem hasn't presented. 
However there is a point in the installation where of a lot of slow internal processing occurs and it is possible that your session is timing out. Activating "Keepalive" in your telnet/ssh client should stop the session timing out.

**Comment by Fyou3** [comment]
> I will have to test an install to make sure a new problem hasn't presented. However there is a point in the installation where of a lot of slow internal processing occurs and it is possible that your session is timing out. Activating "Keepalive" in your telnet/ssh client should stop the session timing out.

My Putty client (ssh) has the option activated "Keepalive".
I leave you a img so you can see the configuration, please see img - > https://i.imgur.com/A3kNMr1.png

I tried seven times to install with such a configuration and I always get the same error  "Network error: Software caused connection abort" at the same point in time in the installation.

**Comment by luckytanuki** [comment]
I suspect the slow install speed is related to the way the installer does rpm queries. Some cpus are slow to process the query. This documented in issue #75 .  I want to have this fixed in the next update.
